// <auto-generated />
namespace jnu_actroom.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ii : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ii));
        
        string IMigrationMetadata.Id
        {
            get { return "201305271439460_ii"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
